name: newzly_app
description: A Flutter news application

publish_to: "none"

version: 1.0.0+1

environment:
 sdk: ">=2.17.0 <4.0.0"

dependencies:
 cupertino_icons: ^1.0.2
 flutter:
  sdk: flutter
 flutter_launcher_icons: ^0.14.4
 http: ^1.4.0
 provider: ^6.1.5
 shared_preferences: ^2.5.3

dev_dependencies:
 flutter_lints: ^2.0.0
 flutter_test:
  sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  # min_sdk_android: 21 # optional
  web:
    generate: true
    image_path: "assets/icons/logo.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/icons/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/logo.png"


flutter:
 uses-material-design: true
